### ISSUE TITLE
compare GraphQL, JSON and RDF representations

### ISSUE THREAD

**Issue by VladimirAlexiev** [Accord-Project/bsdd#2]
- Get a couple of objects of each class. Look for "rich" objects, i.e. maximum fields filled
- Get them in the 3 formats
- Write a comparison table that list all fields per class, are they present in each of the APIs, and comments. Eg:

| **Class**/field            | GraphQL      | JSON API                                   | RDF API                | comment                                                                                                     |
|----------------------------|--------------|--------------------------------------------|------------------------|-------------------------------------------------------------------------------------------------------------|
| **Classification**         |              |                                            |                        |                                                                                                             |
| hierarchy                  | childs       | parentClassificationReference.namespaceUri | NONE                   | GraphQL points to child, JSON points to parent                                                              |
| **ClassificationProperty** |              |                                            |                        | GraphQL and JSON overload the same URL and use it for both ClassificationProperty and Property              |
| link to general property   | namespaceUri | namespaceUri                               | classificationProperty | GraphQL and JSON have no real link, just the overloaded URL. The RDF prop is misnamed, should be "property" |
|                            |              |                                            |                        |                                                                                                             |

In README.org I've added a section **Return the Same Data Across APIs** with the above beginning of a table, showing the org syntax for tables.

**Comment by VladimirAlexiev** [comment]
In addition: make a separate table comparing the fields of `Property` vs `ClassificationProperty`.
- list only the differences
- I hope they are the same across the 3 formats

**Comment by nataschake** [comment]
https://docs.google.com/spreadsheets/d/1z_NRMlExlVuqWhBbSErQ9iiDBY4O_fKMd3avV3-NCmo/edit
