### ISSUE TITLE
extract key fields

### ISSUE THREAD

**Issue by VladimirAlexiev** [Accord-Project/bsdd#6]
- identify all key fields: type, status, etc.  Eg one of the most important ones is `Classification.classificationType` 
- Find all their values
- After data is loaded, make statistical tables how much each value is used
- Try to figure out what each value means, by examining examples

Eg for the above
- CLASS: ok, this is the usual case, it represents components or products
- MATERIAL: ok, it represents materials
- ALTERNATIVE_USE: what's this?
- COMPOSED_PROPERTY: ahem, I don't know how props are composed, but surely not within a Classification?
- DOMAIN: ahem, Domain is a separate class?
- GROUP_OF_PROPERTIES: hmm, there's a string attribute PropSet?
- REFERENCE_DOCUMENT: ahem, there's a ReferenceDocument class, and a string attribute

**Comment by VladimirAlexiev** [comment]
After we load the data to GraphDB:
* write SPARQL queries to count key values, eg
```sparql
select ?type (count(*) as ?c) {
  ?x a bsdd:Classification; bsdd:classificationType ?type
}
```
* Find interesting instances (having unusual values), eg:
```sparql
select ?x ?name ?type {
  ?x a bsdd:Classification; bsdd:classificationType ?type; bsdd:name ?name
  filter(?type not in ("CLASS", "MATERIAL"))
}
```

**Comment by nataschake** [comment]
https://github.com/Accord-Project/bsdd#key-fields
