### ISSUE TITLE
field statistics

### ISSUE THREAD

**Issue by VladimirAlexiev** [Accord-Project/bsdd#7]
What is the fill ratio (i.e. how often is used) each prop of each class?

**Comment by VladimirAlexiev** [comment]
We'll do it after loading RDF, with a SPARQL like
```sparql
select 
  (?x as ?Classification)
  count(?name) as ?name) ... 
{
  ?x a bsdd:Classification
    optional {?x bsdd:name ?name}
    ...
}
```

**Comment by nataschake** [comment]
https://github.com/Accord-Project/bsdd/blob/field-stat/bsdd-Key-fields-statistics.md

**Comment by nataschake** [comment]
Statistics section added to README, it takes everything fro bsdd-key-field-statistics.md and added more..
